

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css'
import AuthProvider from "@/context/AuthProvider";
import { Navbar } from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={`${inter.className} `} >
        <div>
        <AuthProvider>
          <ThemeProvider
          attribute="class"
          defaultTheme="system"
          >
            {children}
            <Toaster position="top-center"/>
          </ThemeProvider>
          </AuthProvider>
        </div>
      </body>
      
      
    </html>
  );
}
